"""add decision intelligence

Revision ID: 05ebf01c252f
Revises: 6ea59f420b23
Create Date: 2026-09-05 23:53:35.677520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ebf01c252f'
down_revision: Union[str, Sequence[str], None] = '6ea59f420b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assumptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumptions_name'), 'assumptions', ['name'], unique=False)
    op.create_index(op.f('ix_assumptions_status'), 'assumptions', ['status'], unique=False)
    op.create_index(op.f('ix_assumptions_workspace_id'), 'assumptions', ['workspace_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_priority'), 'decisions', ['priority'], unique=False)
    op.create_index(op.f('ix_decisions_status'), 'decisions', ['status'], unique=False)
    op.create_index(op.f('ix_decisions_workspace_id'), 'decisions', ['workspace_id'], unique=False)
    op.create_table('decision_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('assumption_id', sa.UUID(), nullable=True),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('dependency_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['assumptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_dependencies_assumption_id'), 'decision_dependencies', ['assumption_id'], unique=False)
    op.create_index(op.f('ix_decision_dependencies_claim_id'), 'decision_dependencies', ['claim_id'], unique=False)
    op.create_index(op.f('ix_decision_dependencies_decision_id'), 'decision_dependencies', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_dependencies_dependency_type'), 'decision_dependencies', ['dependency_type'], unique=False)
    op.create_table('decision_impacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('source_claim_id', sa.UUID(), nullable=True),
    sa.Column('impact_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_claim_id'], ['claims.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_impacts_decision_id'), 'decision_impacts', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_impacts_impact_type'), 'decision_impacts', ['impact_type'], unique=False)
    op.create_index(op.f('ix_decision_impacts_source_claim_id'), 'decision_impacts', ['source_claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_impacts_source_claim_id'), table_name='decision_impacts')
    op.drop_index(op.f('ix_decision_impacts_impact_type'), table_name='decision_impacts')
    op.drop_index(op.f('ix_decision_impacts_decision_id'), table_name='decision_impacts')
    op.drop_table('decision_impacts')
    op.drop_index(op.f('ix_decision_dependencies_dependency_type'), table_name='decision_dependencies')
    op.drop_index(op.f('ix_decision_dependencies_decision_id'), table_name='decision_dependencies')
    op.drop_index(op.f('ix_decision_dependencies_claim_id'), table_name='decision_dependencies')
    op.drop_index(op.f('ix_decision_dependencies_assumption_id'), table_name='decision_dependencies')
    op.drop_table('decision_dependencies')
    op.drop_index(op.f('ix_decisions_workspace_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_status'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_priority'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_assumptions_workspace_id'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_status'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_name'), table_name='assumptions')
    op.drop_table('assumptions')
    # ### end Alembic commands ###
