"""add workspace document hash constraint

Revision ID: a1d9fc449239
Revises: d30be84a1465
Create Date: 2026-09-05 15:59:30.304507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d9fc449239'
down_revision: Union[str, Sequence[str], None] = 'd30be84a1465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_documents_workspace_file_hash', 'documents', ['workspace_id', 'file_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_workspace_file_hash', 'documents', type_='unique')
    # ### end Alembic commands ###
